export {default as store} from './store'
export {default as selectSlicer} from './features/selectSlicer'
export {setSelection, setInput} from './features/selectSlicer'
export {default as userInterfaSlicer} from './features/userInterfaceSlicer'
export { setOpenMnu, setDarkTheme, setTitle } from './features/userInterfaceSlicer'