export {default as store} from './store'
export {default as selectSlicer} from './features/selectSlicer'
export {default as userInterfaSlicer} from './features/userInterfaceSlicer'
export {default as paginationSlicer} from './features/paginationSlicer'
export {setSelection, setInput} from './features/selectSlicer'
export { setOpenMnu, setDarkTheme, setTitle } from './features/userInterfaceSlicer'
export { setCount, setLimit, setOffset, setTotal,setCurrentPage } from './features/paginationSlicer'
